#! /bin/sh

prefix=${NEST_INSTALL_DIR:-/tmp/tmp1}
exec_prefix=${prefix}

usage()
{
    cat <<EOF
Usage: nest-config [OPTION]

Known values for OPTION are:

  --prefix              NEST install prefix for architecture-independent files
  --exec-prefix         NEST install prefix for architecture-dependent files
  --libs                print library linking information
  --cflags              print pre-processor and compiler flags
  --includes            print includes
  --compiler            print the compiler used to compile NEST
  --python-executable   print full path to Python interpreter used
  --python-version      print Python version string for interpreter
  --static-libraries    print "ON" if configured for static libraries, "OFF" otherwise
  --docdir              print the relative path (to prefix) to the installed documentation
  --datadir             print the relative path (to prefix) to the installed data
  --libdir              print the relative path (to prefix) to the installed libraries
  --help                display this help and exit
  --version             output version information

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
        prefix=$optarg
        ;;
    --prefix)
        echo $prefix
        ;;
    --exec-prefix)
        echo $exec_prefix
        ;;
    --version)
        echo "nest-3@7c9ab01"
        ;;
    --help)
        usage 0
        ;;
    --includes)
        echo " -I/tmp/tmp1/include/nest -I/usr/include"
        ;;
    --cflags)
        echo "-fopenmp -fopenmp-targets=nvptx64 -std=c++11 -O2 -Wall -fopenmp=libomp "
        ;;
    --libs)
        echo "-L$prefix/lib64 -lnestutil -lnest -lrandom -lsli -lnestkernel -ltopology -fopenmp=libomp  /lib64/libreadline.so /lib64/libncurses.so    "
        ;;
    --compiler)
        echo "/p/project/cjzam11/kitayama1/opt/clang/current/bin/clang++"
        ;;
    --python-executable)
        echo "/usr/bin/python"
        ;;
    --python-version)
        echo ""
        ;;

    --static-libraries)
        echo "OFF"
        ;;
    --docdir)
        echo "share/doc/nest"
        ;;
    --datadir)
        echo "share/nest"
        ;;
    --libdir)
        echo "lib64"
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done

exit 0
